export const industries = [
  "Agriculture, Forestry and Fishing",
  "Arts, Media and Entertainment",
  "Care",
  "Construction",
  "Education",
  "Energy, Mining, and Utilities",
  "Environmental Protection",
  "Financial Services",
  "Government & Public Administration",
  "Healthcare",
  "Human Resources & Recruitment",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Maintenance Services",
  "Management & Consulting",
  "Manufacturing",
  "Nonprofit & NGOs",
  "Pharmaceutical & Biotechnology",
  "Real Estate",
  "Restaurants & Food Service",
  "Retail & Wholesale",
  "Security",
  "Telecommunications",
  "Tourism",
  "Transportation & Logistics",
];

export const benefits = [
  "ADDITIONAL_SOCIAL_BENEFITS",
  "CHILDCARE_SUPPORT",
  "COMPANY_CAR",
  "COMPANY_PHONE",
  "DENTAL_CARE",
  "DISCOUNTS_FROM_EXTERNAL_PARTNERS",
  "DRINKS_AT_THE_OFFICE",
  "EDUCATION_BUDGET",
  "EMPLOYEE_DISCOUNTS",
  "EMPLOYEE_REFERRAL_PROGRAM",
  "EXTRA_DAYS_OFF",
  "FLEXIBLE_WORKING_HOURS",
  "FREE_MEALS",
  "FRUITS_AT_THE_OFFICE",
  "IT_EQUIPMENT_OF_CHOICE",
  "LANGUAGE_COURSES",
  "LIFE_INSURANCE",
  "PARTIES_AND_EVENTS",
  "PRIVATE_MEDICAL_INSURANCE",
  "RELOCATION_ASSISTANCE",
  "REMOTE_WORK",
  "SUBSIDIED_MEALS",
  "SUBSIDIED_SPORTS",
  "SUBSIDIED_VACATIONS",
];

export const taglines = [
  "Empowering Your Professional Journey.",
  "Connecting Talent with Opportunity.",
  "Rise to Your Full Potential.",
  "Forging Paths to Success Together.",
  "Crafting Your Roadmap to Success.",
  "Reach Your Career Peak with Us.",
  "Building Careers, Shaping Futures.",
  "Climb Higher, Achieve More.",
  "Your Future Starts Here.",
  "Expanding Opportunities, Enriching Lives.",
];
