export const expected = {
  companyName: "",
  tagline: "",
  description: "",
  headquarters: {
    city: "",
    zipCode: "",
    region: "",
    streetName: "",
    streetNumber: "",
    lat: "",
    lng: "",
  },
  email: "",
  phone: "",
  industry: "",
  companyUrl: "",
  benefits: [],
  logoUrl: "",
};
