export default {
  error: "",
  data: [
    {
      id: "pl_887801471",
      user_id: "pl_72181122",
      user_uuid: "fa099726-39a9-4f63-9ef7-df41d000435b",
      country: "",
      category_id: 65,
      status: "active",
      title: "Poznań Pracownik techniczny w Wypożyczalni samochodów",
      description:
        "<p>Nasza historia\n\nKorzenie Kaizen Rent sięgają roku 1979, kiedy to w Lubinie na Dolnym Śląsku powstała firma Dobrygowski Sp. z o.o. Dobrygowski Sp. z o.o. to autoryzowany dealer Toyoty, posiadający 2 salony sprzedaży na Dolnym Śląsku oraz sześciokrotny zdobywca tytułu Dealera Roku. Niesamowite tempo rozwoju salonów Toyota Dobrygowski spowodowało, że Zarząd podjął decyzję o wydzieleniu ze struktury firmy działu flotowego i w 2015 roku powołał do życia spółkę Kaizen Fleet, dając jednocześnie jej pracownikom pełną swobodę działania i realny wpływ na dalszy rozwój spółki. Pod skrzydłami nowego Zarządu spółka rozpoczęła ekspansję, obejmując swoim działaniem całą Polskę. W 2023 roku jesteśmy już w 40 miastach w Polsce a na tym nie koniec...</p>\n<p><strong>Twój zakres obowiązków</strong></p><ul><li><p>Dbanie o flotę w zakresie stanu technicznego i wizualnego pojazdów</p></li><li>Przygotowanie samochodów do wynajmu w zakresie czystości i brandingu (mycie i sprzątanie samochodów na oddziale)</li><li><p>Weryfikacja wyposażenia pojazdów&nbsp;</p></li><li>Obsługa klienta w zakresie wydania i zwrotu samochodów</li></ul>\n<ul><li><p>Prawo jazdy kat. B,</p></li><li><p>Dyspozycyjność od poniedziałku do niedzieli (możliwa praca w systemie 10/12 godzinnym)</p></li><li>Mile widziana praca w 3 weekendy w miesiącu (sobota lub niedziela)</li><li><p>Podstawowa wiedza techniczna z zakresu motoryzacji,</p></li></ul>\n<p><strong>To oferujemy</strong></p><ul><li>Elastyczność, dopasowana do Ciebie i Twoich potrzeb</li><li>Przyjazną atmosferę</li><li>Możliwość zdobycia pierwszych doświadczeń zawodowych, które możesz wpisać do swojego CV. Jesteśmy drugą, największą w Polsce wypożyczalnią samochodów</li><li>Możliwość rozwoju, w ramach struktur danego oddziału</li><li>Zatrudnienie na podstawie umowy zlecenie z określonym systemem wynagrodzeń (stawka godzinowa)&nbsp;</li><li>Bogata oferta benefitów po przepracowaniu 3 miesięcy ( prywatna opieka medyczna, comiesięczny system bonów )</li></ul>\n<p><strong>Klauzula informacyjna Administratora Danych Osobowych&nbsp; </strong><strong>dla Kandydatów </strong></p><p><strong>na pracowników i współpracowników</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>Kaizen Rent S. A. </strong>z siedzibą w Lubinie (59-300) przy ul. Gen. Józefa Bema 8 (KRS: 0000575185) jest Administratorem Danych Osobowych (zwanym dalej <strong>Administratorem</strong>) kandydatów na pracowników i współpracowników, zwanych dalej <strong>Kandydatami</strong>.</li><li>Dane osobowe Kandydatów przetwarzane są przez Administratora w celu:</li><li>przeprowadzenia rekrutacji pracowników i współpracowników,</li><li>na potrzeby przyszłych rekrutacji, pod warunkiem wyrażenia przez Kandydata zgody na takie przetwarzanie.</li><li>Podanie danych osobowych jest dobrowolne, ale niezbędne do uczestnictwa Kandydata w procesie rekrutacji. W szczególności Administrator ma prawo żądać od Kandydatów podania lub udokumentowania danych osobowych wskazanych w art. 221 1 ustawy z dnia 26 czerwca 1974 r. – Kodeks pracy (t. j. Dz.U. z 2018 r. poz. 917, ze zm.) lub danych osobowych niezbędnych do zawarcia umowy cywilnoprawnej.</li><li>Administrator przetwarza dane osobowe przez okres niezbędny do osiągnięcia celów wymienionych w pkt. 2 powyżej. Ponadto, w przypadku wyrażenia przez Kandydata zgody na przetwarzanie danych osobowych na potrzeby przyszłych rekrutacji, o której mowa w pkt. 2 lit. b powyżej, Administrator będzie przetwarzał takie dane we wskazanym celu przez okres trzech lat od dnia wyrażenia takiej zgody lub do czasu wycofania zgody przez Kandydata. Dane osobowe mogą być przetwarzane przez okres dłuższy niż wskazany w niniejszym punkcie, w przypadku gdy taki obowiązek nałożony na Administratora wynika ze szczególnych przepisów prawa.</li><li>Źródłem danych osobowych przetwarzanych przez Administratora są Kandydaci, tj. osoby, których dane dotyczą.</li><li>Podstawą prawną przetwarzania danych osobowych Kandydatów jest:</li><li>6 ust. 1 lit. b RODO, tj. niezbędność do podjęcia działań na żądanie Kandydata przed zawarciem umowy, lub</li><li>6 ust. 1 lit. a RODO, tj. zgoda Kandydata na przetwarzanie danych osobowych w określonych celach, gdy inne podstawy prawne przetwarzania danych osobowych nie mają zastosowania, co dotyczy przede wszystkim przetwarzania szczególnych kategorii danych osobowych (danych wrażliwych) Kandydata oraz przetwarzania danych Kandydata na potrzeby przyszłych rekrutacji.</li><li>Dane osobowe Kandydatów nie są przekazywane do państwa trzeciego w rozumieniu przepisów RODO. W przypadku, gdyby dane osobowe były przekazywane do państwa trzeciego, Kandydaci zostaną o tym uprzednio poinformowani, a Administrator będzie stosować zabezpieczenia, o których mowa w rozdziale V RODO.</li><li>Administrator nie udostępnia danych osobowych podmiotom trzecim bez wyraźnej zgody osoby, której dane dotyczą. Dane osobowe bez zgody osoby, której dane dotyczą, mogą być udostępniane wyłącznie podmiotom prawa publicznego, tj. organom władzy i administracji (np. organom podatkowym, organom ścigania i innym podmiotom posiadającym umocowanie w powszechnie obowiązujących przepisach prawa, takim jak ZUS czy Urząd Skarbowy) w przypadkach przewidzianych przez powszechnie obowiązujące przepisy prawa.</li><li>Dane osobowe Kandydatów nie podlegają profilowaniu przez Administratora w rozumieniu przepisów RODO.</li><li>Zgodnie z przepisami RODO Kandydaci mają prawo do:</li><li>bycia informowanym o przetwarzaniu danych osobowych, o którym mowa w art. 12 RODO,</li><li>dostępu do swoich danych osobowych, o którym mowa w art. 15 RODO,</li><li>poprawiania, uzupełniania, uaktualniania, sprostowania danych osobowych, o których mowa w art. 16 RODO,</li><li>usunięcia danych (prawo do bycia zapomnianym), o którym mowa w art. 17 RODO,</li><li>ograniczenia przetwarzania, o którym mowa w art. 18 RODO,</li><li>przenoszenia danych, o którym mowa w art. 20 RODO,</li><li>wniesienia sprzeciwu od przetwarzania danych osobowych, o czym mowa w art. 21 RODO,</li><li>w przypadku podstawy prawnej, o której mowa w pkt. 7 lit. b powyżej – prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem,</li><li>niepodlegania proﬁlowaniu, o którym mowa w art. 22 w zw. z art. 4 pkt 4 RODO,</li><li>wniesienia skargi do organu nadzorczego (tj. do Prezesa Urzędu Ochrony Danych Osobowych), o którym mowa w art. 77 RODO,</li></ul><p>z uwzględnieniem zasad korzystania i realizowania tych uprawnień wynikających z przepisów RODO.</p>Jeżeli Kandydaci chcą skorzystać ze swoich praw, o których mowa w punkcie poprzedzającym, powinni przesłać wiadomość drogą poczty elektronicznej lub w formie pisemnej na adres e-mail lub adres korespondencyjny, o których mowa w pkt. 12 poniżej.Administrator powołał Inspektora Ochrony Danych, którym jest Konrad Cioczek Wszelkie zapytania, wnioski i skargi dotyczące przetwarzania danych osobowych przez Administratora, zwane dalej Zgłoszeniami, należy kierować na adres e-mail: rodo(at.)kaizenrent.pl lub w formie pisemnej na następujący adres Administratora: ul. Gen. Józefa Bema 8 w Lubinie (59-300).W treści Zgłoszenia należy w sposób wyraźny wskazać:dane osoby lub osób, których dotyczy Zgłoszenie,zdarzenie, które jest powodem Zgłoszenia,przedstawić swoje żądania oraz podstawę prawną tych żądań,wskazać oczekiwany sposób załatwienia sprawy.<p>&nbsp;</p>",
      url: "https://www.olx.pl/oferta/praca/poznan-pracownik-techniczny-w-wypozyczalni-samochodow-CID4-IDY57Iz.html",
      apply_url:
        "https://system.erecruiter.pl/FormTemplates/RecruitmentForm.aspx?WebID=d281da0ef2164251b984a007cfc86b3d&joid=178617&source=olx",
      location: {
        region_id: 1,
        city_id: 13983,
        district_id: 323,
        city_name: "Poznań",
        district_name: "Grunwald",
        latitude: 52.40119,
        longitude: 16.88433,
        radius: 2,
      },
      salary: {
        type: "",
        from: 0,
        to: 0,
        amount: 0,
        currency: "",
        arranged: 0,
      },
      raw_parameters: [
        { code: "agreement", value: ["zlecenie"] },
        { code: "experience", value: ["exp_yes"] },
        { code: "availability", value: ["weekends_work", "flexible_work"] },
        { code: "workplace", value: ["on_site"] },
        { code: "manager", value: ["0"] },
        { code: "remote_recruitment", value: ["1"] },
        { code: "senior_friendly", value: ["0"] },
        { code: "type", value: ["fulltime"] },
      ],
      ttl: "2024-08-01T09:55:02Z",
      added_at: "2024-01-23T10:57:04Z",
      changed_at: "2024-01-23T10:57:04.381Z",
      valid_to: "2024-02-01T09:55:02Z",
      is_business: true,
      is_seek: false,
      langs: ["pl"],
      categories: { pl: "Pozostałe oferty pracy" },
      parameters: {
        pl: [
          {
            code: "agreement",
            label: "Typ umowy",
            values: [{ code: "zlecenie", label: "Umowa zlecenie" }],
          },
          {
            code: "experience",
            label: "Wymagane doświadczenie",
            values: [{ code: "exp_yes", label: "Wymagane doświadczenie" }],
          },
          {
            code: "availability",
            label: "Dyspozycyjność",
            values: [
              { code: "weekends_work", label: "Praca w weekendy" },
              { code: "flexible_work", label: "Elastyczny czas pracy" },
            ],
          },
          {
            code: "workplace",
            label: "Miejsce pracy",
            values: [{ code: "on_site", label: "W siedzibie firmy" }],
          },
          { code: "manager", label: "Kadra kierownicza" },
          {
            code: "remote_recruitment",
            label: "Rekrutacja online",
            enabled: true,
          },
          { code: "senior_friendly", label: "Zapraszamy seniorów" },
          {
            code: "type",
            label: "Wymiar pracy",
            values: [{ code: "fulltime", label: "Pełny etat" }],
          },
        ],
      },
      external_partner_code: "",
    },
    {
      id: "pl_888065497",
      user_id: "pl_72181122",
      user_uuid: "fa099726-39a9-4f63-9ef7-df41d000435b",
      country: "",
      category_id: 2510,
      status: "active",
      title:
        "Lotnisko Gdańsk-Agent obsługi lotniskowej w wypożyczalni samochodów",
      description:
        "<p>Nasza historia&nbsp;</p><p>Korzenie Kaizen Rent sięgają roku 1979, kiedy to w Lubinie na Dolnym Śląsku powstała firma Dobrygowski Sp. z o.o. Dobrygowski Sp. z o.o. to autoryzowany dealer Toyoty, posiadający 2 salony sprzedaży na Dolnym Śląsku oraz sześciokrotny zdobywca tytułu Dealera Roku. Niesamowite tempo rozwoju salonów Toyota Dobrygowski spowodowało, że Zarząd podjął decyzję o wydzieleniu ze struktury firmy działu flotowego i w 2015 roku powołał do życia spółkę Kaizen Fleet, dając jednocześnie jej pracownikom pełną swobodę działania i realny wpływ na dalszy rozwój spółki. Pod skrzydłami nowego Zarządu spółka rozpoczęła ekspansję, obejmując swoim działaniem całą Polskę. W 2023 roku jesteśmy już w 40 miastach w Polsce a na tym nie koniec...</p>\n<p><strong>Opis stanowiska:</strong></p><p>Czym się będziesz zajmować:</p><p>- Obsługa klienta w języku polskim oraz angielskim (telefoniczna, mailowa, osobista)</p><p>- Pozyskiwanie nowych klientów,</p><p>- Budowanie i utrzymanie relacji ze stałymi klientami firmy</p><p>- Realizacja miesięcznych planów sprzedaży</p><p>- Obsługa aplikacji mobilnej</p><p>- Obsługa systemu wewnętrznego</p><p>- Obsługa terminala kart płatniczych</p><p>- Dbanie o dobry wizerunek firmy</p><p>- Dbanie o wysoką jakość usług w oparciu o standardy firmy</p><p>- Dbanie o stan techniczny samochodów</p><p>- Raportowanie</p>\n<p>Nasze wymagania:</p><p>- Bardzo dobra znajomości języka angielskiego w mowie i piśmie</p><p>- Wysoka kultura osobista</p><p>- Gotowość do pracy zmianowej, również w weekendy</p><p>- Prawo jazdy kategorii B</p><p>- Umiejętność pracy w grupie</p><p>- Dobra organizacja czasu pracy</p><p>- Punktualność, uczciwość, zaangażowanie, samodzielność</p><p>- Doświadczenie w obsłudze klienta</p>\n<p>Co oferujemy:</p><p>- Pracę w młodym zespole</p><p>- Rabat na wynajem samochodów w naszej firmie</p><p>- Niezbędne narzędzia pracy</p><p>- Atrakcyjne wynagrodzenie uzależnione od wyników</p><p>- Bogatą ofertę benefitów (prywatna opieka medyczna, comiesięczny system bonów)</p><p>- Przyjazną atmosferę</p><p>- Możliwość rozwoju w strukturach firmy</p>\n<p><strong>Klauzula informacyjna Administratora Danych Osobowych&nbsp; </strong><strong>dla Kandydatów </strong></p><p><strong>na pracowników i współpracowników</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>Kaizen Rent S. A. </strong>z siedzibą w Lubinie (59-300) przy ul. Gen. Józefa Bema 8 (KRS: 0000575185) jest Administratorem Danych Osobowych (zwanym dalej <strong>Administratorem</strong>) kandydatów na pracowników i współpracowników, zwanych dalej <strong>Kandydatami</strong>.</li><li>Dane osobowe Kandydatów przetwarzane są przez Administratora w celu:</li><li>przeprowadzenia rekrutacji pracowników i współpracowników,</li><li>na potrzeby przyszłych rekrutacji, pod warunkiem wyrażenia przez Kandydata zgody na takie przetwarzanie.</li><li>Podanie danych osobowych jest dobrowolne, ale niezbędne do uczestnictwa Kandydata w procesie rekrutacji. W szczególności Administrator ma prawo żądać od Kandydatów podania lub udokumentowania danych osobowych wskazanych w art. 221 1 ustawy z dnia 26 czerwca 1974 r. – Kodeks pracy (t. j. Dz.U. z 2018 r. poz. 917, ze zm.) lub danych osobowych niezbędnych do zawarcia umowy cywilnoprawnej.</li><li>Administrator przetwarza dane osobowe przez okres niezbędny do osiągnięcia celów wymienionych w pkt. 2 powyżej. Ponadto, w przypadku wyrażenia przez Kandydata zgody na przetwarzanie danych osobowych na potrzeby przyszłych rekrutacji, o której mowa w pkt. 2 lit. b powyżej, Administrator będzie przetwarzał takie dane we wskazanym celu przez okres trzech lat od dnia wyrażenia takiej zgody lub do czasu wycofania zgody przez Kandydata. Dane osobowe mogą być przetwarzane przez okres dłuższy niż wskazany w niniejszym punkcie, w przypadku gdy taki obowiązek nałożony na Administratora wynika ze szczególnych przepisów prawa.</li><li>Źródłem danych osobowych przetwarzanych przez Administratora są Kandydaci, tj. osoby, których dane dotyczą.</li><li>Podstawą prawną przetwarzania danych osobowych Kandydatów jest:</li><li>6 ust. 1 lit. b RODO, tj. niezbędność do podjęcia działań na żądanie Kandydata przed zawarciem umowy, lub</li><li>6 ust. 1 lit. a RODO, tj. zgoda Kandydata na przetwarzanie danych osobowych w określonych celach, gdy inne podstawy prawne przetwarzania danych osobowych nie mają zastosowania, co dotyczy przede wszystkim przetwarzania szczególnych kategorii danych osobowych (danych wrażliwych) Kandydata oraz przetwarzania danych Kandydata na potrzeby przyszłych rekrutacji.</li><li>Dane osobowe Kandydatów nie są przekazywane do państwa trzeciego w rozumieniu przepisów RODO. W przypadku, gdyby dane osobowe były przekazywane do państwa trzeciego, Kandydaci zostaną o tym uprzednio poinformowani, a Administrator będzie stosować zabezpieczenia, o których mowa w rozdziale V RODO.</li><li>Administrator nie udostępnia danych osobowych podmiotom trzecim bez wyraźnej zgody osoby, której dane dotyczą. Dane osobowe bez zgody osoby, której dane dotyczą, mogą być udostępniane wyłącznie podmiotom prawa publicznego, tj. organom władzy i administracji (np. organom podatkowym, organom ścigania i innym podmiotom posiadającym umocowanie w powszechnie obowiązujących przepisach prawa, takim jak ZUS czy Urząd Skarbowy) w przypadkach przewidzianych przez powszechnie obowiązujące przepisy prawa.</li><li>Dane osobowe Kandydatów nie podlegają profilowaniu przez Administratora w rozumieniu przepisów RODO.</li><li>Zgodnie z przepisami RODO Kandydaci mają prawo do:</li><li>bycia informowanym o przetwarzaniu danych osobowych, o którym mowa w art. 12 RODO,</li><li>dostępu do swoich danych osobowych, o którym mowa w art. 15 RODO,</li><li>poprawiania, uzupełniania, uaktualniania, sprostowania danych osobowych, o których mowa w art. 16 RODO,</li><li>usunięcia danych (prawo do bycia zapomnianym), o którym mowa w art. 17 RODO,</li><li>ograniczenia przetwarzania, o którym mowa w art. 18 RODO,</li><li>przenoszenia danych, o którym mowa w art. 20 RODO,</li><li>wniesienia sprzeciwu od przetwarzania danych osobowych, o czym mowa w art. 21 RODO,</li><li>w przypadku podstawy prawnej, o której mowa w pkt. 7 lit. b powyżej – prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem,</li><li>niepodlegania proﬁlowaniu, o którym mowa w art. 22 w zw. z art. 4 pkt 4 RODO,</li><li>wniesienia skargi do organu nadzorczego (tj. do Prezesa Urzędu Ochrony Danych Osobowych), o którym mowa w art. 77 RODO,</li></ul><p>z uwzględnieniem zasad korzystania i realizowania tych uprawnień wynikających z przepisów RODO.</p>Jeżeli Kandydaci chcą skorzystać ze swoich praw, o których mowa w punkcie poprzedzającym, powinni przesłać wiadomość drogą poczty elektronicznej lub w formie pisemnej na adres e-mail lub adres korespondencyjny, o których mowa w pkt. 12 poniżej.Administrator powołał Inspektora Ochrony Danych, którym jest Konrad Cioczek Wszelkie zapytania, wnioski i skargi dotyczące przetwarzania danych osobowych przez Administratora, zwane dalej Zgłoszeniami, należy kierować na adres e-mail: rodo(at.)kaizenrent.pl lub w formie pisemnej na następujący adres Administratora: ul. Gen. Józefa Bema 8 w Lubinie (59-300).W treści Zgłoszenia należy w sposób wyraźny wskazać:dane osoby lub osób, których dotyczy Zgłoszenie,zdarzenie, które jest powodem Zgłoszenia,przedstawić swoje żądania oraz podstawę prawną tych żądań,wskazać oczekiwany sposób załatwienia sprawy.<p>&nbsp;</p>",
      url: "https://www.olx.pl/oferta/praca/lotnisko-gdansk-agent-obslugi-lotniskowej-w-wypozyczalni-samochodow-CID4-IDY6ep3.html",
      apply_url:
        "https://system.erecruiter.pl/FormTemplates/RecruitmentForm.aspx?WebID=2361bb7c519e400893dd00379f34505b&joid=178911&source=olx",
      location: {
        region_id: 5,
        city_id: 5659,
        district_id: 105,
        city_name: "Gdańsk",
        district_name: "Matarnia",
        latitude: 54.35208,
        longitude: 18.43542,
        radius: 13,
      },
      salary: {
        type: "",
        from: 0,
        to: 0,
        amount: 0,
        currency: "",
        arranged: 0,
      },
      raw_parameters: [
        { code: "manager", value: ["0"] },
        { code: "remote_recruitment", value: ["1"] },
        { code: "senior_friendly", value: ["0"] },
        { code: "type", value: ["fulltime"] },
        { code: "agreement", value: ["zlecenie"] },
        { code: "experience", value: ["exp_yes"] },
        {
          code: "availability",
          value: ["flexible_work", "shift_work", "weekends_work"],
        },
        { code: "workplace", value: ["on_site"] },
      ],
      ttl: "2024-08-02T09:07:18Z",
      added_at: "2024-01-24T10:09:30Z",
      changed_at: "2024-01-24T10:09:30.454Z",
      valid_to: "2024-02-02T09:07:18Z",
      is_business: true,
      is_seek: false,
      langs: ["pl"],
      categories: { pl: "Specjalista ds. obsługi klienta" },
      parameters: {
        pl: [
          { code: "manager", label: "Kadra kierownicza" },
          {
            code: "remote_recruitment",
            label: "Rekrutacja online",
            enabled: true,
          },
          { code: "senior_friendly", label: "Zapraszamy seniorów" },
          {
            code: "type",
            label: "Wymiar pracy",
            values: [{ code: "fulltime", label: "Pełny etat" }],
          },
          {
            code: "agreement",
            label: "Typ umowy",
            values: [{ code: "zlecenie", label: "Umowa zlecenie" }],
          },
          {
            code: "experience",
            label: "Wymagane doświadczenie",
            values: [{ code: "exp_yes", label: "Wymagane doświadczenie" }],
          },
          {
            code: "availability",
            label: "Dyspozycyjność",
            values: [
              { code: "flexible_work", label: "Elastyczny czas pracy" },
              { code: "shift_work", label: "Praca zmianowa" },
              { code: "weekends_work", label: "Praca w weekendy" },
            ],
          },
          {
            code: "workplace",
            label: "Miejsce pracy",
            values: [{ code: "on_site", label: "W siedzibie firmy" }],
          },
        ],
      },
      external_partner_code: "",
    },
    {
      id: "pl_888089801",
      user_id: "pl_72181122",
      user_uuid: "fa099726-39a9-4f63-9ef7-df41d000435b",
      country: "",
      category_id: 65,
      status: "active",
      title: "Łódź Pracownik techniczny w wypożyczalni samochodów",
      description:
        "<p>Nasza historia\n\nKorzenie Kaizen Rent sięgają roku 1979, kiedy to w Lubinie na Dolnym Śląsku powstała firma Dobrygowski Sp. z o.o. Dobrygowski Sp. z o.o. to autoryzowany dealer Toyoty, posiadający 2 salony sprzedaży na Dolnym Śląsku oraz sześciokrotny zdobywca tytułu Dealera Roku. Niesamowite tempo rozwoju salonów Toyota Dobrygowski spowodowało, że Zarząd podjął decyzję o wydzieleniu ze struktury firmy działu flotowego i w 2015 roku powołał do życia spółkę Kaizen Fleet, dając jednocześnie jej pracownikom pełną swobodę działania i realny wpływ na dalszy rozwój spółki. Pod skrzydłami nowego Zarządu spółka rozpoczęła ekspansję, obejmując swoim działaniem całą Polskę. W 2023 roku jesteśmy już w 40 miastach w Polsce a na tym nie koniec...</p>\n<p><strong>Twój zakres obowiązków</strong></p><ul><li><p>Dbanie o flotę w zakresie stanu technicznego i wizualnego pojazdów</p></li><li>Przygotowanie samochodów do wynajmu w zakresie czystości i brandingu (mycie i sprzątanie samochodów na oddziale)</li><li><p>Weryfikacja wyposażenia pojazdów&nbsp;</p></li><li>Obsługa klienta w zakresie wydania i zwrotu samochodów</li></ul>\n<ul><li><p>Prawo jazdy kat. B,</p></li><li><p>Dyspozycyjność od poniedziałku do niedzieli (możliwa praca w systemie 10/12 godzinnym)</p></li><li>Mile widziana praca w 2 weekendy w miesiącu (sobota lub niedziela)</li><li><p>Podstawowa wiedza techniczna z zakresu motoryzacji,</p></li></ul>\n<p><strong>To oferujemy</strong></p><ul><li>Elastyczność, dopasowana do Ciebie i Twoich potrzeb</li><li>Przyjazną atmosferę</li><li>Możliwość zdobycia pierwszych doświadczeń zawodowych, które możesz wpisać do swojego CV. Jesteśmy drugą, największą w Polsce wypożyczalnią samochodów</li><li>Możliwość rozwoju, w ramach struktur danego oddziału</li><li>Zatrudnienie na podstawie umowy zlecenie z określonym systemem wynagrodzeń (stawka godzinowa)&nbsp;</li><li>Bogata oferta benefitów po przepracowaniu 3 miesięcy (prywatna opieka medyczna, comiesięczny system bonów)</li></ul>\n<p><strong>Klauzula informacyjna Administratora Danych Osobowych&nbsp; </strong><strong>dla Kandydatów </strong></p><p><strong>na pracowników i współpracowników</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>Kaizen Rent S. A. </strong>z siedzibą w Lubinie (59-300) przy ul. Gen. Józefa Bema 8 (KRS: 0000575185) jest Administratorem Danych Osobowych (zwanym dalej <strong>Administratorem</strong>) kandydatów na pracowników i współpracowników, zwanych dalej <strong>Kandydatami</strong>.</li><li>Dane osobowe Kandydatów przetwarzane są przez Administratora w celu:</li><li>przeprowadzenia rekrutacji pracowników i współpracowników,</li><li>na potrzeby przyszłych rekrutacji, pod warunkiem wyrażenia przez Kandydata zgody na takie przetwarzanie.</li><li>Podanie danych osobowych jest dobrowolne, ale niezbędne do uczestnictwa Kandydata w procesie rekrutacji. W szczególności Administrator ma prawo żądać od Kandydatów podania lub udokumentowania danych osobowych wskazanych w art. 221 1 ustawy z dnia 26 czerwca 1974 r. – Kodeks pracy (t. j. Dz.U. z 2018 r. poz. 917, ze zm.) lub danych osobowych niezbędnych do zawarcia umowy cywilnoprawnej.</li><li>Administrator przetwarza dane osobowe przez okres niezbędny do osiągnięcia celów wymienionych w pkt. 2 powyżej. Ponadto, w przypadku wyrażenia przez Kandydata zgody na przetwarzanie danych osobowych na potrzeby przyszłych rekrutacji, o której mowa w pkt. 2 lit. b powyżej, Administrator będzie przetwarzał takie dane we wskazanym celu przez okres trzech lat od dnia wyrażenia takiej zgody lub do czasu wycofania zgody przez Kandydata. Dane osobowe mogą być przetwarzane przez okres dłuższy niż wskazany w niniejszym punkcie, w przypadku gdy taki obowiązek nałożony na Administratora wynika ze szczególnych przepisów prawa.</li><li>Źródłem danych osobowych przetwarzanych przez Administratora są Kandydaci, tj. osoby, których dane dotyczą.</li><li>Podstawą prawną przetwarzania danych osobowych Kandydatów jest:</li><li>6 ust. 1 lit. b RODO, tj. niezbędność do podjęcia działań na żądanie Kandydata przed zawarciem umowy, lub</li><li>6 ust. 1 lit. a RODO, tj. zgoda Kandydata na przetwarzanie danych osobowych w określonych celach, gdy inne podstawy prawne przetwarzania danych osobowych nie mają zastosowania, co dotyczy przede wszystkim przetwarzania szczególnych kategorii danych osobowych (danych wrażliwych) Kandydata oraz przetwarzania danych Kandydata na potrzeby przyszłych rekrutacji.</li><li>Dane osobowe Kandydatów nie są przekazywane do państwa trzeciego w rozumieniu przepisów RODO. W przypadku, gdyby dane osobowe były przekazywane do państwa trzeciego, Kandydaci zostaną o tym uprzednio poinformowani, a Administrator będzie stosować zabezpieczenia, o których mowa w rozdziale V RODO.</li><li>Administrator nie udostępnia danych osobowych podmiotom trzecim bez wyraźnej zgody osoby, której dane dotyczą. Dane osobowe bez zgody osoby, której dane dotyczą, mogą być udostępniane wyłącznie podmiotom prawa publicznego, tj. organom władzy i administracji (np. organom podatkowym, organom ścigania i innym podmiotom posiadającym umocowanie w powszechnie obowiązujących przepisach prawa, takim jak ZUS czy Urząd Skarbowy) w przypadkach przewidzianych przez powszechnie obowiązujące przepisy prawa.</li><li>Dane osobowe Kandydatów nie podlegają profilowaniu przez Administratora w rozumieniu przepisów RODO.</li><li>Zgodnie z przepisami RODO Kandydaci mają prawo do:</li><li>bycia informowanym o przetwarzaniu danych osobowych, o którym mowa w art. 12 RODO,</li><li>dostępu do swoich danych osobowych, o którym mowa w art. 15 RODO,</li><li>poprawiania, uzupełniania, uaktualniania, sprostowania danych osobowych, o których mowa w art. 16 RODO,</li><li>usunięcia danych (prawo do bycia zapomnianym), o którym mowa w art. 17 RODO,</li><li>ograniczenia przetwarzania, o którym mowa w art. 18 RODO,</li><li>przenoszenia danych, o którym mowa w art. 20 RODO,</li><li>wniesienia sprzeciwu od przetwarzania danych osobowych, o czym mowa w art. 21 RODO,</li><li>w przypadku podstawy prawnej, o której mowa w pkt. 7 lit. b powyżej – prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem,</li><li>niepodlegania proﬁlowaniu, o którym mowa w art. 22 w zw. z art. 4 pkt 4 RODO,</li><li>wniesienia skargi do organu nadzorczego (tj. do Prezesa Urzędu Ochrony Danych Osobowych), o którym mowa w art. 77 RODO,</li></ul><p>z uwzględnieniem zasad korzystania i realizowania tych uprawnień wynikających z przepisów RODO.</p>Jeżeli Kandydaci chcą skorzystać ze swoich praw, o których mowa w punkcie poprzedzającym, powinni przesłać wiadomość drogą poczty elektronicznej lub w formie pisemnej na adres e-mail lub adres korespondencyjny, o których mowa w pkt. 12 poniżej.Administrator powołał Inspektora Ochrony Danych, którym jest Konrad Cioczek Wszelkie zapytania, wnioski i skargi dotyczące przetwarzania danych osobowych przez Administratora, zwane dalej Zgłoszeniami, należy kierować na adres e-mail: rodo(at.)kaizenrent.pl lub w formie pisemnej na następujący adres Administratora: ul. Gen. Józefa Bema 8 w Lubinie (59-300).W treści Zgłoszenia należy w sposób wyraźny wskazać:dane osoby lub osób, których dotyczy Zgłoszenie,zdarzenie, które jest powodem Zgłoszenia,przedstawić swoje żądania oraz podstawę prawną tych żądań,wskazać oczekiwany sposób załatwienia sprawy.<p>&nbsp;</p>",
      url: "https://www.olx.pl/oferta/praca/lodz-pracownik-techniczny-w-wypozyczalni-samochodow-CID4-IDY6kJ3.html",
      apply_url:
        "https://system.erecruiter.pl/FormTemplates/RecruitmentForm.aspx?WebID=4f6184e1f7124701b284501d08d610b4&joid=178971&source=olx",
      location: {
        region_id: 7,
        city_id: 10609,
        district_id: 299,
        city_name: "Łódź",
        district_name: "Śródmieście",
        latitude: 51.7691,
        longitude: 19.46617,
        radius: 7.5,
      },
      salary: {
        type: "",
        from: 0,
        to: 0,
        amount: 0,
        currency: "",
        arranged: 0,
      },
      raw_parameters: [
        { code: "availability", value: ["flexible_work", "weekends_work"] },
        { code: "workplace", value: ["on_site"] },
        { code: "manager", value: ["0"] },
        { code: "remote_recruitment", value: ["1"] },
        { code: "senior_friendly", value: ["0"] },
        { code: "type", value: ["fulltime"] },
        { code: "agreement", value: ["zlecenie"] },
        { code: "experience", value: ["exp_yes"] },
      ],
      ttl: "2024-08-02T10:43:23Z",
      added_at: "2024-01-24T11:45:27Z",
      changed_at: "2024-01-24T11:45:27.679Z",
      valid_to: "2024-02-02T10:43:23Z",
      is_business: true,
      is_seek: false,
      langs: ["pl"],
      categories: { pl: "Pozostałe oferty pracy" },
      parameters: {
        pl: [
          {
            code: "availability",
            label: "Dyspozycyjność",
            values: [
              { code: "flexible_work", label: "Elastyczny czas pracy" },
              { code: "weekends_work", label: "Praca w weekendy" },
            ],
          },
          {
            code: "workplace",
            label: "Miejsce pracy",
            values: [{ code: "on_site", label: "W siedzibie firmy" }],
          },
          { code: "manager", label: "Kadra kierownicza" },
          {
            code: "remote_recruitment",
            label: "Rekrutacja online",
            enabled: true,
          },
          { code: "senior_friendly", label: "Zapraszamy seniorów" },
          {
            code: "type",
            label: "Wymiar pracy",
            values: [{ code: "fulltime", label: "Pełny etat" }],
          },
          {
            code: "agreement",
            label: "Typ umowy",
            values: [{ code: "zlecenie", label: "Umowa zlecenie" }],
          },
          {
            code: "experience",
            label: "Wymagane doświadczenie",
            values: [{ code: "exp_yes", label: "Wymagane doświadczenie" }],
          },
        ],
      },
      external_partner_code: "",
    },
    {
      id: "pl_888136960",
      user_id: "pl_72181122",
      user_uuid: "fa099726-39a9-4f63-9ef7-df41d000435b",
      country: "",
      category_id: 65,
      status: "active",
      title: "Piła Przedstawiciel Wypożyczalni Samochodów (kierowca)",
      description:
        "<p>Nasza historia\n\nKorzenie Kaizen Rent sięgają roku 1979, kiedy to w Lubinie na Dolnym Śląsku powstała firma Dobrygowski Sp. z o.o. Dobrygowski Sp. z o.o. to autoryzowany dealer Toyoty, posiadający 2 salony sprzedaży na Dolnym Śląsku oraz sześciokrotny zdobywca tytułu Dealera Roku. Niesamowite tempo rozwoju salonów Toyota Dobrygowski spowodowało, że Zarząd podjął decyzję o wydzieleniu ze struktury firmy działu flotowego i w 2015 roku powołał do życia spółkę Kaizen Fleet, dając jednocześnie jej pracownikom pełną swobodę działania i realny wpływ na dalszy rozwój spółki. Pod skrzydłami nowego Zarządu spółka rozpoczęła ekspansję, obejmując swoim działaniem całą Polskę. W 2023 roku jesteśmy już w 40 miastach w Polsce, a na tym nie koniec...</p>\n<p><strong>Twój zakres obowiązków</strong></p><ul><li>Praca 5 dni w tygodniu</li><li>Tylko w tym czasie będziemy Cię prosili o odebranie lub podstawienie samochodu do naszych klientów</li><li>Możemy Cię też prosić o dostarczenie samochodu do innego oddziału lub serwisu</li><li>Będziesz również odpowiedzialny za podstawienie samochodu do myjni, zatankowanie, czy zgłoszenie usterek. Chcemy, abyś jeżdżąc naszymi samochodami czuł się bezpiecznie, tak jak nasi klienci</li><li>Zapewnimy Ci wszystkie niezbędne do pracy narzędzia. Tablet, nawigację, wsparcie ze strony Biura Obsługi Klienta, pracowników oddziałów, czy serwisu</li></ul>\n<ul><li>Prawo jazdy kat. B</li><li>Dyspozycyjność od poniedziałku do piątku (możliwa praca w trybie 12 godzinnym)</li><li>Mile widziana dyspozycyjność w weekendy,&nbsp;</li><li>Podstawowa wiedza techniczna z zakresu motoryzacji,</li><li>Kreatywność w rozwiązywaniu problemów,&nbsp;</li><li>Dobra organizacja pracy,&nbsp;</li><li>Punktualność, uczciwość, zaangażowanie, samodzielność</li><li>Dobra znajomość angielskiego</li></ul>\n<p>Co oferujemy?&nbsp;</p><ul><li>Elastyczność, dopasowaną do Ciebie i Twoich potrzeb,</li><li>Przyjazną atmosferę,&nbsp;</li><li>Możliwość zdobycia pierwszych doświadczeń zawodowych, które możesz wpisać do swojego CV. Jesteśmy drugą, największą w Polsce wypożyczalnią samochodów,&nbsp;</li><li>Możliwość rozwoju, w ramach struktur danego oddziału,&nbsp;</li><li>Zatrudnienie na podstawie umowy zlecenia z określonym systemem wynagrodzeń&nbsp;</li><li>Bogata oferta benefitów po przepracowaniu 3 miesięcy (prywatna opieka medyczna, comiesięczny system bonów)</li></ul>\n<p><strong>Klauzula informacyjna Administratora Danych Osobowych&nbsp; </strong><strong>dla Kandydatów </strong></p><p><strong>na pracowników i współpracowników</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>Kaizen Rent S. A. </strong>z siedzibą w Lubinie (59-300) przy ul. Gen. Józefa Bema 8 (KRS: 0000575185) jest Administratorem Danych Osobowych (zwanym dalej <strong>Administratorem</strong>) kandydatów na pracowników i współpracowników, zwanych dalej <strong>Kandydatami</strong>.</li><li>Dane osobowe Kandydatów przetwarzane są przez Administratora w celu:</li><li>przeprowadzenia rekrutacji pracowników i współpracowników,</li><li>na potrzeby przyszłych rekrutacji, pod warunkiem wyrażenia przez Kandydata zgody na takie przetwarzanie.</li><li>Podanie danych osobowych jest dobrowolne, ale niezbędne do uczestnictwa Kandydata w procesie rekrutacji. W szczególności Administrator ma prawo żądać od Kandydatów podania lub udokumentowania danych osobowych wskazanych w art. 221 1 ustawy z dnia 26 czerwca 1974 r. – Kodeks pracy (t. j. Dz.U. z 2018 r. poz. 917, ze zm.) lub danych osobowych niezbędnych do zawarcia umowy cywilnoprawnej.</li><li>Administrator przetwarza dane osobowe przez okres niezbędny do osiągnięcia celów wymienionych w pkt. 2 powyżej. Ponadto, w przypadku wyrażenia przez Kandydata zgody na przetwarzanie danych osobowych na potrzeby przyszłych rekrutacji, o której mowa w pkt. 2 lit. b powyżej, Administrator będzie przetwarzał takie dane we wskazanym celu przez okres trzech lat od dnia wyrażenia takiej zgody lub do czasu wycofania zgody przez Kandydata. Dane osobowe mogą być przetwarzane przez okres dłuższy niż wskazany w niniejszym punkcie, w przypadku gdy taki obowiązek nałożony na Administratora wynika ze szczególnych przepisów prawa.</li><li>Źródłem danych osobowych przetwarzanych przez Administratora są Kandydaci, tj. osoby, których dane dotyczą.</li><li>Podstawą prawną przetwarzania danych osobowych Kandydatów jest:</li><li>6 ust. 1 lit. b RODO, tj. niezbędność do podjęcia działań na żądanie Kandydata przed zawarciem umowy, lub</li><li>6 ust. 1 lit. a RODO, tj. zgoda Kandydata na przetwarzanie danych osobowych w określonych celach, gdy inne podstawy prawne przetwarzania danych osobowych nie mają zastosowania, co dotyczy przede wszystkim przetwarzania szczególnych kategorii danych osobowych (danych wrażliwych) Kandydata oraz przetwarzania danych Kandydata na potrzeby przyszłych rekrutacji.</li><li>Dane osobowe Kandydatów nie są przekazywane do państwa trzeciego w rozumieniu przepisów RODO. W przypadku, gdyby dane osobowe były przekazywane do państwa trzeciego, Kandydaci zostaną o tym uprzednio poinformowani, a Administrator będzie stosować zabezpieczenia, o których mowa w rozdziale V RODO.</li><li>Administrator nie udostępnia danych osobowych podmiotom trzecim bez wyraźnej zgody osoby, której dane dotyczą. Dane osobowe bez zgody osoby, której dane dotyczą, mogą być udostępniane wyłącznie podmiotom prawa publicznego, tj. organom władzy i administracji (np. organom podatkowym, organom ścigania i innym podmiotom posiadającym umocowanie w powszechnie obowiązujących przepisach prawa, takim jak ZUS czy Urząd Skarbowy) w przypadkach przewidzianych przez powszechnie obowiązujące przepisy prawa.</li><li>Dane osobowe Kandydatów nie podlegają profilowaniu przez Administratora w rozumieniu przepisów RODO.</li><li>Zgodnie z przepisami RODO Kandydaci mają prawo do:</li><li>bycia informowanym o przetwarzaniu danych osobowych, o którym mowa w art. 12 RODO,</li><li>dostępu do swoich danych osobowych, o którym mowa w art. 15 RODO,</li><li>poprawiania, uzupełniania, uaktualniania, sprostowania danych osobowych, o których mowa w art. 16 RODO,</li><li>usunięcia danych (prawo do bycia zapomnianym), o którym mowa w art. 17 RODO,</li><li>ograniczenia przetwarzania, o którym mowa w art. 18 RODO,</li><li>przenoszenia danych, o którym mowa w art. 20 RODO,</li><li>wniesienia sprzeciwu od przetwarzania danych osobowych, o czym mowa w art. 21 RODO,</li><li>w przypadku podstawy prawnej, o której mowa w pkt. 7 lit. b powyżej – prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem,</li><li>niepodlegania proﬁlowaniu, o którym mowa w art. 22 w zw. z art. 4 pkt 4 RODO,</li><li>wniesienia skargi do organu nadzorczego (tj. do Prezesa Urzędu Ochrony Danych Osobowych), o którym mowa w art. 77 RODO,</li></ul><p>z uwzględnieniem zasad korzystania i realizowania tych uprawnień wynikających z przepisów RODO.</p>Jeżeli Kandydaci chcą skorzystać ze swoich praw, o których mowa w punkcie poprzedzającym, powinni przesłać wiadomość drogą poczty elektronicznej lub w formie pisemnej na adres e-mail lub adres korespondencyjny, o których mowa w pkt. 12 poniżej.Administrator powołał Inspektora Ochrony Danych, którym jest Konrad Cioczek Wszelkie zapytania, wnioski i skargi dotyczące przetwarzania danych osobowych przez Administratora, zwane dalej Zgłoszeniami, należy kierować na adres e-mail: rodo(at.)kaizenrent.pl lub w formie pisemnej na następujący adres Administratora: ul. Gen. Józefa Bema 8 w Lubinie (59-300).W treści Zgłoszenia należy w sposób wyraźny wskazać:dane osoby lub osób, których dotyczy Zgłoszenie,zdarzenie, które jest powodem Zgłoszenia,przedstawić swoje żądania oraz podstawę prawną tych żądań,wskazać oczekiwany sposób załatwienia sprawy.<p>&nbsp;</p>",
      url: "https://www.olx.pl/oferta/praca/pila-przedstawiciel-wypozyczalni-samochodow-kierowca-CID4-IDY6vZG.html",
      apply_url:
        "https://system.erecruiter.pl/FormTemplates/RecruitmentForm.aspx?WebID=908c2b8591c549abbc9912032ead6ecf&joid=179061&source=olx",
      location: {
        region_id: 1,
        city_id: 52515,
        city_name: "Piła",
        latitude: 53.15324,
        longitude: 16.73333,
        radius: 5.25,
      },
      salary: {
        type: "",
        from: 0,
        to: 0,
        amount: 0,
        currency: "",
        arranged: 0,
      },
      raw_parameters: [
        { code: "agreement", value: ["zlecenie"] },
        { code: "experience", value: ["exp_yes"] },
        {
          code: "availability",
          value: ["flexible_work", "weekends_work", "shift_work"],
        },
        { code: "workplace", value: ["on_site"] },
        { code: "manager", value: ["0"] },
        { code: "remote_recruitment", value: ["1"] },
        { code: "senior_friendly", value: ["0"] },
        { code: "type", value: ["fulltime"] },
      ],
      ttl: "2024-08-02T13:14:13Z",
      added_at: "2024-01-24T14:16:31Z",
      changed_at: "2024-01-24T14:16:31.337Z",
      valid_to: "2024-02-02T13:14:13Z",
      is_business: true,
      is_seek: false,
      langs: ["pl"],
      categories: { pl: "Pozostałe oferty pracy" },
      parameters: {
        pl: [
          {
            code: "agreement",
            label: "Typ umowy",
            values: [{ code: "zlecenie", label: "Umowa zlecenie" }],
          },
          {
            code: "experience",
            label: "Wymagane doświadczenie",
            values: [{ code: "exp_yes", label: "Wymagane doświadczenie" }],
          },
          {
            code: "availability",
            label: "Dyspozycyjność",
            values: [
              { code: "flexible_work", label: "Elastyczny czas pracy" },
              { code: "weekends_work", label: "Praca w weekendy" },
              { code: "shift_work", label: "Praca zmianowa" },
            ],
          },
          {
            code: "workplace",
            label: "Miejsce pracy",
            values: [{ code: "on_site", label: "W siedzibie firmy" }],
          },
          { code: "manager", label: "Kadra kierownicza" },
          {
            code: "remote_recruitment",
            label: "Rekrutacja online",
            enabled: true,
          },
          { code: "senior_friendly", label: "Zapraszamy seniorów" },
          {
            code: "type",
            label: "Wymiar pracy",
            values: [{ code: "fulltime", label: "Pełny etat" }],
          },
        ],
      },
      external_partner_code: "",
    },
    {
      id: "pl_889571733",
      user_id: "pl_72181122",
      user_uuid: "fa099726-39a9-4f63-9ef7-df41d000435b",
      country: "",
      category_id: 65,
      status: "active",
      title:
        "Płock Przedstawiciel Wypożyczalni Samochodów (kierowca-praca 12-23)",
      description:
        "<p>Nasza historia\n\nKorzenie Kaizen Rent sięgają roku 1979, kiedy to w Lubinie na Dolnym Śląsku powstała firma Dobrygowski Sp. z o.o. Dobrygowski Sp. z o.o. to autoryzowany dealer Toyoty, posiadający 2 salony sprzedaży na Dolnym Śląsku oraz sześciokrotny zdobywca tytułu Dealera Roku. Niesamowite tempo rozwoju salonów Toyota Dobrygowski spowodowało, że Zarząd podjął decyzję o wydzieleniu ze struktury firmy działu flotowego i w 2015 roku powołał do życia spółkę Kaizen Fleet, dając jednocześnie jej pracownikom pełną swobodę działania i realny wpływ na dalszy rozwój spółki. Pod skrzydłami nowego Zarządu spółka rozpoczęła ekspansję, obejmując swoim działaniem całą Polskę. W 2023 roku jesteśmy już w 40 miastach w Polsce, a na tym nie koniec...</p>\n<p><strong>Twój zakres obowiązków</strong></p><ul><li>Praca 5 dni w tygodniu ( godziny popołudniowo-wieczorne 12-23)</li><li>Tylko w tym czasie będziemy Cię prosili o odebranie lub podstawienie samochodu do naszych klientów</li><li>Możemy Cię też prosić o dostarczenie samochodu do innego oddziału lub serwisu</li><li>Będziesz również odpowiedzialny za podstawienie samochodu do myjni, zatankowanie, czy zgłoszenie usterek. Chcemy, abyś jeżdżąc naszymi samochodami czuł się bezpiecznie, tak jak nasi klienci</li><li>Zapewnimy Ci wszystkie niezbędne do pracy narzędzia. Tablet, nawigację, wsparcie ze strony Biura Obsługi Klienta, pracowników oddziałów, czy serwisu</li></ul>\n<ul><li>Prawo jazdy kat. B</li><li>Dyspozycyjność od poniedziałku do piątku (możliwa praca w trybie 12 godzinnym)</li><li>Mile widziana dyspozycyjność w weekendy,&nbsp;</li><li>Podstawowa wiedza techniczna z zakresu motoryzacji,</li><li>Kreatywność w rozwiązywaniu problemów,&nbsp;</li><li>Dobra organizacja pracy,&nbsp;</li><li>Punktualność, uczciwość, zaangażowanie, samodzielność</li><li>Dobra znajomość angielskiego</li></ul>\n<p>Co oferujemy?&nbsp;</p><ul><li>Elastyczność, dopasowaną do Ciebie i Twoich potrzeb,</li><li>Przyjazną atmosferę,&nbsp;</li><li>Możliwość zdobycia pierwszych doświadczeń zawodowych, które możesz wpisać do swojego CV. Jesteśmy drugą, największą w Polsce wypożyczalnią samochodów,&nbsp;</li><li>Możliwość rozwoju, w ramach struktur danego oddziału,&nbsp;</li><li>Zatrudnienie na podstawie umowy zlecenia z określonym systemem wynagrodzeń&nbsp;</li><li>Bogata oferta benefitów po przepracowaniu 3 miesięcy (prywatna opieka medyczna, comiesięczny system bonów)</li></ul>\n<p><strong>Klauzula informacyjna Administratora Danych Osobowych&nbsp; </strong><strong>dla Kandydatów </strong></p><p><strong>na pracowników i współpracowników</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>Kaizen Rent S. A. </strong>z siedzibą w Lubinie (59-300) przy ul. Gen. Józefa Bema 8 (KRS: 0000575185) jest Administratorem Danych Osobowych (zwanym dalej <strong>Administratorem</strong>) kandydatów na pracowników i współpracowników, zwanych dalej <strong>Kandydatami</strong>.</li><li>Dane osobowe Kandydatów przetwarzane są przez Administratora w celu:</li><li>przeprowadzenia rekrutacji pracowników i współpracowników,</li><li>na potrzeby przyszłych rekrutacji, pod warunkiem wyrażenia przez Kandydata zgody na takie przetwarzanie.</li><li>Podanie danych osobowych jest dobrowolne, ale niezbędne do uczestnictwa Kandydata w procesie rekrutacji. W szczególności Administrator ma prawo żądać od Kandydatów podania lub udokumentowania danych osobowych wskazanych w art. 221 1 ustawy z dnia 26 czerwca 1974 r. – Kodeks pracy (t. j. Dz.U. z 2018 r. poz. 917, ze zm.) lub danych osobowych niezbędnych do zawarcia umowy cywilnoprawnej.</li><li>Administrator przetwarza dane osobowe przez okres niezbędny do osiągnięcia celów wymienionych w pkt. 2 powyżej. Ponadto, w przypadku wyrażenia przez Kandydata zgody na przetwarzanie danych osobowych na potrzeby przyszłych rekrutacji, o której mowa w pkt. 2 lit. b powyżej, Administrator będzie przetwarzał takie dane we wskazanym celu przez okres trzech lat od dnia wyrażenia takiej zgody lub do czasu wycofania zgody przez Kandydata. Dane osobowe mogą być przetwarzane przez okres dłuższy niż wskazany w niniejszym punkcie, w przypadku gdy taki obowiązek nałożony na Administratora wynika ze szczególnych przepisów prawa.</li><li>Źródłem danych osobowych przetwarzanych przez Administratora są Kandydaci, tj. osoby, których dane dotyczą.</li><li>Podstawą prawną przetwarzania danych osobowych Kandydatów jest:</li><li>6 ust. 1 lit. b RODO, tj. niezbędność do podjęcia działań na żądanie Kandydata przed zawarciem umowy, lub</li><li>6 ust. 1 lit. a RODO, tj. zgoda Kandydata na przetwarzanie danych osobowych w określonych celach, gdy inne podstawy prawne przetwarzania danych osobowych nie mają zastosowania, co dotyczy przede wszystkim przetwarzania szczególnych kategorii danych osobowych (danych wrażliwych) Kandydata oraz przetwarzania danych Kandydata na potrzeby przyszłych rekrutacji.</li><li>Dane osobowe Kandydatów nie są przekazywane do państwa trzeciego w rozumieniu przepisów RODO. W przypadku, gdyby dane osobowe były przekazywane do państwa trzeciego, Kandydaci zostaną o tym uprzednio poinformowani, a Administrator będzie stosować zabezpieczenia, o których mowa w rozdziale V RODO.</li><li>Administrator nie udostępnia danych osobowych podmiotom trzecim bez wyraźnej zgody osoby, której dane dotyczą. Dane osobowe bez zgody osoby, której dane dotyczą, mogą być udostępniane wyłącznie podmiotom prawa publicznego, tj. organom władzy i administracji (np. organom podatkowym, organom ścigania i innym podmiotom posiadającym umocowanie w powszechnie obowiązujących przepisach prawa, takim jak ZUS czy Urząd Skarbowy) w przypadkach przewidzianych przez powszechnie obowiązujące przepisy prawa.</li><li>Dane osobowe Kandydatów nie podlegają profilowaniu przez Administratora w rozumieniu przepisów RODO.</li><li>Zgodnie z przepisami RODO Kandydaci mają prawo do:</li><li>bycia informowanym o przetwarzaniu danych osobowych, o którym mowa w art. 12 RODO,</li><li>dostępu do swoich danych osobowych, o którym mowa w art. 15 RODO,</li><li>poprawiania, uzupełniania, uaktualniania, sprostowania danych osobowych, o których mowa w art. 16 RODO,</li><li>usunięcia danych (prawo do bycia zapomnianym), o którym mowa w art. 17 RODO,</li><li>ograniczenia przetwarzania, o którym mowa w art. 18 RODO,</li><li>przenoszenia danych, o którym mowa w art. 20 RODO,</li><li>wniesienia sprzeciwu od przetwarzania danych osobowych, o czym mowa w art. 21 RODO,</li><li>w przypadku podstawy prawnej, o której mowa w pkt. 7 lit. b powyżej – prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania, którego dokonano na podstawie zgody przed jej cofnięciem,</li><li>niepodlegania proﬁlowaniu, o którym mowa w art. 22 w zw. z art. 4 pkt 4 RODO,</li><li>wniesienia skargi do organu nadzorczego (tj. do Prezesa Urzędu Ochrony Danych Osobowych), o którym mowa w art. 77 RODO,</li></ul><p>z uwzględnieniem zasad korzystania i realizowania tych uprawnień wynikających z przepisów RODO.</p>Jeżeli Kandydaci chcą skorzystać ze swoich praw, o których mowa w punkcie poprzedzającym, powinni przesłać wiadomość drogą poczty elektronicznej lub w formie pisemnej na adres e-mail lub adres korespondencyjny, o których mowa w pkt. 12 poniżej.Administrator powołał Inspektora Ochrony Danych, którym jest Konrad Cioczek Wszelkie zapytania, wnioski i skargi dotyczące przetwarzania danych osobowych przez Administratora, zwane dalej Zgłoszeniami, należy kierować na adres e-mail: rodo(at.)kaizenrent.pl lub w formie pisemnej na następujący adres Administratora: ul. Gen. Józefa Bema 8 w Lubinie (59-300).W treści Zgłoszenia należy w sposób wyraźny wskazać:dane osoby lub osób, których dotyczy Zgłoszenie,zdarzenie, które jest powodem Zgłoszenia,przedstawić swoje żądania oraz podstawę prawną tych żądań,wskazać oczekiwany sposób załatwienia sprawy.<p>&nbsp;</p>",
      url: "https://www.olx.pl/oferta/praca/plock-przedstawiciel-wypozyczalni-samochodow-kierowca-praca-12-23-CID4-IDYcyfb.html",
      apply_url:
        "https://system.erecruiter.pl/FormTemplates/RecruitmentForm.aspx?WebID=52adefe499f847f4a5f5b9fb75343303&joid=180343&source=olx",
      location: {
        region_id: 2,
        city_id: 13663,
        city_name: "Płock",
        latitude: 52.54635,
        longitude: 19.70654,
        radius: 6,
      },
      salary: {
        type: "",
        from: 0,
        to: 0,
        amount: 0,
        currency: "",
        arranged: 0,
      },
      raw_parameters: [
        { code: "type", value: ["fulltime"] },
        { code: "agreement", value: ["zlecenie"] },
        { code: "experience", value: ["exp_yes"] },
        {
          code: "availability",
          value: ["flexible_work", "weekends_work", "shift_work"],
        },
        { code: "workplace", value: ["on_site"] },
        { code: "manager", value: ["0"] },
        { code: "remote_recruitment", value: ["1"] },
        { code: "senior_friendly", value: ["0"] },
      ],
      ttl: "2024-08-08T12:32:29Z",
      added_at: "2024-01-30T13:34:31Z",
      changed_at: "2024-01-30T13:34:31.367Z",
      valid_to: "2024-02-08T12:32:29Z",
      is_business: true,
      is_seek: false,
      langs: ["pl"],
      categories: { pl: "Pozostałe oferty pracy" },
      parameters: {
        pl: [
          {
            code: "type",
            label: "Wymiar pracy",
            values: [{ code: "fulltime", label: "Pełny etat" }],
          },
          {
            code: "agreement",
            label: "Typ umowy",
            values: [{ code: "zlecenie", label: "Umowa zlecenie" }],
          },
          {
            code: "experience",
            label: "Wymagane doświadczenie",
            values: [{ code: "exp_yes", label: "Wymagane doświadczenie" }],
          },
          {
            code: "availability",
            label: "Dyspozycyjność",
            values: [
              { code: "flexible_work", label: "Elastyczny czas pracy" },
              { code: "weekends_work", label: "Praca w weekendy" },
              { code: "shift_work", label: "Praca zmianowa" },
            ],
          },
          {
            code: "workplace",
            label: "Miejsce pracy",
            values: [{ code: "on_site", label: "W siedzibie firmy" }],
          },
          { code: "manager", label: "Kadra kierownicza" },
          {
            code: "remote_recruitment",
            label: "Rekrutacja online",
            enabled: true,
          },
          { code: "senior_friendly", label: "Zapraszamy seniorów" },
        ],
      },
      external_partner_code: "",
    },
  ],
};
